import {
  Category,
  CategoryComplete,
} from '../../categories/models/category.model';

// Generated by https://quicktype.io

export interface ProductResponse {
  id: number;
  title: string;
  price: number;
  description: string;
  category: Category;
  images: string[];
}

export interface ProductCreateRequest {
  title: string;
  price: number;
  description: string;
  categoryId: number;
  images: string[];
}

// Generated by https://quicktype.io

export interface ProductCreateResponse {
  category: CategoryComplete;
  creationAt: string;
  description: string;
  id: number;
  images: string[];
  price: number;
  title: string;
  updatedAt: string;
}

// Generated by https://quicktype.io

export interface ProductUpdateRequest {
  id?: number;
  title: string;
  price: number;
}
